x-base_service: &base_service
  ports:
    - "${WEBUI_PORT:-7860}:7860"
  volumes:
    - &v1 ./data:/data
    - &v2 ./output:/output
  stop_signal: SIGKILL
  tty: true

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:7
    devices:
      - nvidia.com/gpu=all
    environment:
      - CLI_ARGS=
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    environment:
      - CLI_ARGS=--cpu
